version: "3"
services:

    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        ports:
            - "0.0.0.0:1883:1883"
            - "0.0.0.0:9001:9001"
        volumes:
            - ./mosquitto:/mosquitto/config

    core:
        container_name: core
        image: thinkfree84/ax5_core:latest
        build:
            context: ../
            dockerfile: src/core/Dockerfile
        environment:
            - broker=mosquitto
        depends_on:
            - mosquitto
        volumes:
            - ./ax5:/ax5

    alarm:
        container_name: alarm
        image: thinkfree84/ax5_alarm:latest
        build:
            context: ../
            dockerfile: src/tasks/alarm/Dockerfile
        environment:
            - broker=mosquitto
            - host=alarm
            - port=8123
        depends_on:
            - mosquitto
        ports:
            - "0.0.0.0:8123:8123"
        volumes:
            - ./ax5:/ax5

    time:
        container_name: time
        image: thinkfree84/ax5_time:latest
        build:
            context: ../
            dockerfile: src/devices/time/Dockerfile
        environment:
            - broker=mosquitto
            - homeId=home
            - group=server
            - instance=time
        depends_on:
            - mosquitto
        volumes:
            - ./ax5:/ax5
