version: "3"
services:

    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        ports:
            - "0.0.0.0:1883:1883"
            - "0.0.0.0:9001:9001"
        volumes:
            - ./mosquitto:/mosquitto/config

    core:
        container_name: core
        image: thinkfree84/ax5_core:latest
        build: ../core/
        volumes:
            - ./ax5:/ax5
