version: "3"
services:
    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        ports:
            - "0.0.0.0:1883:1883"
            - "0.0.0.0:9001:9001"
        volumes:
            - ./mosquitto:/mosquitto
        networks:
            - net

    core:
        container_name: core
        image: thinkfree84/ax5_core:latest
        build:
            context: ../
            dockerfile: src/core/Dockerfile
        environment:
            - AX_BROKER=mosquitto
        depends_on:
            - mosquitto
        ports:
            - "0.0.0.0:8080:8080"
        volumes:
            - ./config:/etc/ax5
        networks:
            - net

    admin:
        container_name: admin
        image: thinkfree84/ax5_admin:latest
        build:
            context: ../
            dockerfile: src/plugins/admin/Dockerfile
        environment:
            - AX_BROKER=mosquitto
            - AX_HOST=admin
            - AX_PORT=8123
        depends_on:
            - mosquitto
        volumes:
            - ./config:/etc/ax5
            - ./plugins:/etc/plugins
        networks:
            - net

networks:
  net:
    driver: bridge
